### build for ARM9 linux 
export PATH=/usr/local/arm-2014.05/bin/:$PATH

arm-none-linux-gnueabi-gcc -g -static -lpthread -lm  -L/opt/nuc970bsp/applications/tslib-1.1/install/lib/ -lts  \
-I/opt/nuc970bsp/applications/tslib-1.1/install/include \
-I./Config/ -I./GUI/Core/ -I./GUI/Widget/ -I./GUI/WM/ \
./Simulation/FrameBuffer_main.c \
./Simulation/GUI_X_Linux.c \
./GUI/Core/GUIUC0.c \
./GUI/Core/GUI_SetPixelIndex.c \
./GUI/Core/GUI_DrawBitmap.c \
./GUI/Core/GUI__Arabic.c \
./GUI/Core/GUI_DispStringInRect.c \
./GUI/Core/GUI_DispCEOL.c \
./GUI/Core/LCD_API.c \
./GUI/Core/LCDP888_Index2Color.c \
./GUI/Core/GUI_GetFont.c \
./GUI/Core/GUICirc.c \
./GUI/Core/GUI_Pen.c \
./GUI/Core/LCDRLE8.c \
./GUI/Core/GUI_DispStringHCenter.c \
./GUI/Core/LCD_GetPixelColor.c \
./GUI/Core/GUI__ReduceRect.c \
./GUI/Core/GUI_CursorArrowMI.c \
./GUI/Core/LCDP565_Index2Color.c \
./GUI/Core/LCD_MixColors256.c \
./GUI/Core/GUI__strlen.c \
./GUI/Core/LCD_SetAPI.c \
./GUI/Core/GUI_MergeRect.c \
./GUI/Core/GUI_DrawVLine.c \
./GUI/Core/GUI_GetStringDistX.c \
./GUI/Core/GUI_FillPolygon.c \
./GUI/Core/LCDAA.c \
./GUI/Core/GUI_DrawGraphEx.c \
./GUI/Core/LCD_RotateCW.c \
./GUI/Core/GUI_DrawPolyline.c \
./GUI/Core/GUI__GetCursorPos.c \
./GUI/Core/GUI_Goto.c \
./GUI/Core/GUITask.c \
./GUI/Core/GUI_CursorCrossL.c \
./GUI/Core/GUI_CursorArrowSI.c \
./GUI/Core/GUI_DrawPoint.c \
./GUI/Core/GUI_CursorArrowS.c \
./GUI/Core/GUI_TOUCH.c \
./GUI/Core/GUI_DrawBitmapExp.c \
./GUI/Core/GUI__memset16.c \
./GUI/Core/LCD_Rotate180.c \
./GUI/Core/GUIStream.c \
./GUI/Core/GUI_CursorCrossMI.c \
./GUI/Core/GUICurs.c \
./GUI/Core/GUI_Warn.c \
./GUI/Core/GUI_ALLOC_AllocZero.c \
./GUI/Core/GUI_AddKeyMsgHook.c \
./GUI/Core/GUI__IntersectRect.c \
./GUI/Core/GUI_UC.c \
./GUI/Core/GUI_CursorArrowMPx.c \
./GUI/Core/GUI__SetText.c \
./GUI/Core/GUI_SetLUTEntry.c \
./GUI/Core/GUI_SetTextMode.c \
./GUI/Core/GUI_AddBin.c \
./GUI/Core/GUI_MOUSE.c \
./GUI/Core/GUI__CalcTextRect.c \
./GUI/Core/GUI__GetNumChars.c \
./GUI/Core/LCDInfo.c \
./GUI/Core/LCDInfo0.c \
./GUI/Core/GUI_DrawBitmap_565.c \
./GUI/Core/GUICharM.c \
./GUI/Core/GUI_WaitKey.c \
./GUI/Core/GUI_SetFont.c \
./GUI/Core/GUI_CursorArrowSPx.c \
./GUI/Core/LCDPM565_Index2Color.c \
./GUI/Core/GUI_GetBitmapPixelIndex.c \
./GUI/Core/GUIPolyR.c \
./GUI/Core/GUI_DrawBitmapMag.c \
./GUI/Core/GUI_CursorCrossLPx.c \
./GUI/Core/LCD_GetNumDisplays.c \
./GUI/Core/GUI_DrawFocusRect.c \
./GUI/Core/GUICharP.c \
./GUI/Core/GUI_CursorPalI.c \
./GUI/Core/GUI_DrawHLine.c \
./GUI/Core/LCD_GetColorIndex.c \
./GUI/Core/GUI_DispChar.c \
./GUI/Core/GUI__strcmp.c \
./GUI/Core/GUIValf.c \
./GUI/Core/GUI_MoveRect.c \
./GUI/Core/GUI_GetDrawMode.c \
./GUI/Core/GUI_SetColor.c \
./GUI/Core/LCD_UpdateColorIndices.c \
./GUI/Core/GUI_ErrorOut.c \
./GUI/Core/GUITimer.c \
./GUI/Core/GUI_GetFontInfo.c \
./GUI/Core/GUI_DrawBitmap_555.c \
./GUI/Core/GUI_FillRectEx.c \
./GUI/Core/GUI_UC_EncodeUTF8.c \
./GUI/Core/GUI_UC_EncodeNone.c \
./GUI/Core/GUI_SetDecChar.c \
./GUI/Core/GUI__DivideRound.c \
./GUI/Core/GUI_SetOrg.c \
./GUI/Core/GUI_GetYSizeOfFont.c \
./GUI/Core/GUI_AddHex.c \
./GUI/Core/GUI_AddDecMin.c \
./GUI/Core/LCD_ReadRect.c \
./GUI/Core/GUI_CalcColorDist.c \
./GUI/Core/GUI_GetTextMode.c \
./GUI/Core/GUI_Log.c \
./GUI/Core/GUI_SetTextStyle.c \
./GUI/Core/GUI_CursorCrossSPx.c \
./GUI/Core/GUI_OnKey.c \
./GUI/Core/GUI_AddDec.c \
./GUI/Core/GUIEncJS.c \
./GUI/Core/LCD_GetEx.c \
./GUI/Core/GUI_DrawPixel.c \
./GUI/Core/GUI_CursorHeaderMPx.c \
./GUI/Core/GUI2DLib.c \
./GUI/Core/GUI_RectsIntersect.c \
./GUI/Core/GUI_TOUCH_DriverAnalog.c \
./GUI/Core/GUIArc.c \
./GUI/Core/LCD_SetClipRectEx.c \
./GUI/Core/GUI_InvertRect.c \
./GUI/Core/GUI__DivideRound32.c \
./GUI/Core/GUI_CursorCrossMPx.c \
./GUI/Core/GUI_SetLBorder.c \
./GUI/Core/GUI_WaitEvent.c \
./GUI/Core/GUI_DispChars.c \
./GUI/Core/GUI_DrawBitmapEx.c \
./GUI/Core/GUI__DrawBitmap16bpp.c \
./GUI/Core/GUI_PID.c \
./GUI/Core/GUIIndex2Color.c \
./GUI/Core/GUI_CursorCrossS.c \
./GUI/Core/GUIChar.c \
./GUI/Core/LCDPM888_Index2Color.c \
./GUI/Core/LCDRLE4.c \
./GUI/Core/GUI_GetTextExtend.c \
./GUI/Core/LCD_SelectLCD.c \
./GUI/Core/GUI__HandleEOLine.c \
./GUI/Core/LCD_RotateCCW.c \
./GUI/Core/GUI_GetColor.c \
./GUI/Core/LCDL0Mag.c \
./GUI/Core/LCDP1.c \
./GUI/Core/GUI_FillRect.c \
./GUI/Core/GUI__Read.c \
./GUI/Core/GUI__AddSpaceHex.c \
./GUI/Core/GUI_GetBitmapPixelColor.c \
./GUI/Core/GUI_SetDefault.c \
./GUI/Core/GUITime.c \
./GUI/Core/GUI_DispHex.c \
./GUI/Core/GUI_Color2VisColor.c \
./GUI/Core/GUI_GetDispPos.c \
./GUI/Core/GUIRealloc.c \
./GUI/Core/GUI_CursorCrossM.c \
./GUI/Core/GUI_InitLUT.c \
./GUI/Core/GUI_TOUCH_StoreState.c \
./GUI/Core/LCD_Mirror.c \
./GUI/Core/GUI_ScreenSize.c \
./GUI/Core/GUI__Wrap.c \
./GUI/Core/GUIPolyM.c \
./GUI/Core/GUI_SelectLayer.c \
./GUI/Core/GUI_CursorArrowL.c \
./GUI/Core/GUI_BMP_Serialize.c \
./GUI/Core/GUI_SetColorIndex.c \
./GUI/Core/GUI_DispStringAt.c \
./GUI/Core/LCD.c \
./GUI/Core/GUIColor2Index.c \
./GUI/Core/GUI_SetClipRect.c \
./GUI/Core/GUI_SetDrawMode.c \
./GUI/Core/GUI_DrawLine.c \
./GUI/Core/GUI_CursorHeaderM.c \
./GUI/Core/GUI_GetLineStyle.c \
./GUI/Core/GUI_GIF.c \
./GUI/Core/LCDL0Delta.c \
./GUI/Core/GUI_DrawRectEx.c \
./GUI/Core/GUI_BMP.c \
./GUI/Core/LCDColor.c \
./GUI/Core/GUI_IsInFont.c \
./GUI/Core/LCD_Index2ColorEx.c \
./GUI/Core/GUIAlloc.c \
./GUI/Core/LCDInfo1.c \
./GUI/Core/GUI_SetLUTColorEx.c \
./GUI/Core/GUI_DrawPolygon.c \
./GUI/Core/GUI_CursorHeaderMI.c \
./GUI/Core/GUI_GetFontSizeY.c \
./GUI/Core/LCDGetP.c \
./GUI/Core/GUI_DrawBitmap_888.c \
./GUI/Core/GUIVal.c \
./GUI/Core/GUI_SetTextAlign.c \
./GUI/Core/GUI_GetOrg.c \
./GUI/Core/LCDRLE16.c \
./GUI/Core/GUI_DispBin.c \
./GUI/Core/GUI_DispStringAtCEOL.c \
./GUI/Core/LCD_DrawVLine.c \
./GUI/Core/GUI_GetTextAlign.c \
./GUI/Core/GUI_AddDecShift.c \
./GUI/Core/GUICharLine.c \
./GUI/Core/GUICore.c \
./GUI/Core/GUI_UC_ConvertUTF82UC.c \
./GUI/Core/GUI_SelectLCD.c \
./GUI/Core/GUI_SaveContext.c \
./GUI/Core/GUI_DispStringLen.c \
./GUI/Core/GUI__IntersectRects.c \
./GUI/Core/GUI_SetLineStyle.c \
./GUI/Core/GUI_DispStringInRectEx.c \
./GUI/Core/GUI_DrawPie.c \
./GUI/Core/GUI_TOUCH_StoreUnstable.c \
./GUI/Core/GUI_GetClientRect.c \
./GUI/Core/GUI_DispString.c \
./GUI/Core/GUI_UC_ConvertUC2UTF8.c \
./GUI/Core/GUI_CursorCrossLI.c \
./GUI/Core/GUI_ALLOC_AllocInit.c \
./GUI/Core/GUI_CursorPal.c \
./GUI/Core/GUIPolyE.c \
./GUI/Core/GUI__GetFontSizeY.c \
./GUI/Core/GUI_GetVersionString.c \
./GUI/Core/GUI_CursorArrowM.c \
./GUI/Core/GUI_DispStringInRectWrap.c \
./GUI/Core/GUI_CursorArrowLI.c \
./GUI/Core/GUI_UC_DispString.c \
./GUI/Core/GUI_Exec.c \
./GUI/Core/GUI_CursorCrossSI.c \
./GUI/Core/GUI_CursorArrowLPx.c \
./GUI/Core/GUI_MOUSE_DriverPS2.c \
./GUI/Core/GUI__memset.c \
./GUI/Core/GUI_SIF_Prop.c \
./GUI/Core/GUI_SetLUTColor.c \
./GUI/Core/GUI_SIF.c \
./GUI/Core/GUI_ClearRectEx.c \
./GUI/Core/GUI_DrawGraph.c \
./GUI/AntiAlias/GUIAAChar4.c \
./GUI/AntiAlias/GUIAAPoly.c \
./GUI/AntiAlias/GUIAALine.c \
./GUI/AntiAlias/GUIAAPolyOut.c \
./GUI/AntiAlias/GUIAAChar.c \
./GUI/AntiAlias/GUIAAChar2.c \
./GUI/AntiAlias/GUIAALib.c \
./GUI/AntiAlias/GUIAAArc.c \
./GUI/AntiAlias/GUIAACircle.c \
./GUI/WM/WM_IsFocussable.c \
./GUI/WM/WM_GetScrollPos.c \
./GUI/WM/WM_SetTrans.c \
./GUI/WM/WM_SetXSize.c \
./GUI/WM/WM_HasCaptured.c \
./GUI/WM/WM__Screen2Client.c \
./GUI/WM/WM_GetNextSibling.c \
./GUI/WM/WM_GetFocussedWindow.c \
./GUI/WM/WM_GetClientRect.c \
./GUI/WM/WM_GetDiagInfo.c \
./GUI/WM/WM_MakeModal.c \
./GUI/WM/WM_SetFocusOnNextChild.c \
./GUI/WM/WM__GetOrg_AA.c \
./GUI/WM/WM_GetCallback.c \
./GUI/WM/WM__SendMessage.c \
./GUI/WM/WM_SetFocus.c \
./GUI/WM/WM_GetBkColor.c \
./GUI/WM/WM_SetId.c \
./GUI/WM/WM__SendMessageNoPara.c \
./GUI/WM/WMMemDev.c \
./GUI/WM/WM_SendMessageNoPara.c \
./GUI/WM/WM_SetCapture.c \
./GUI/WM/WM_SetDesktopColor.c \
./GUI/WM/WM_SetWindowPos.c \
./GUI/WM/WM_UserData.c \
./GUI/WM/WM_GetScrollState.c \
./GUI/WM/WM.c \
./GUI/WM/WM_ValidateWindow.c \
./GUI/WM/WM_SetScrollPos.c \
./GUI/WM/WM_InvalidateArea.c \
./GUI/WM/WM_GetDesktopWindow.c \
./GUI/WM/WM_ForEachDesc.c \
./GUI/WM/WM_DIAG.c \
./GUI/WM/WM__UpdateChildPositions.c \
./GUI/WM/WM_SendToParent.c \
./GUI/WM/WM_IsCompletelyVisible.c \
./GUI/WM/WM_IsVisible.c \
./GUI/WM/WM_SetCaptureMove.c \
./GUI/WM/WM_IsWindow.c \
./GUI/WM/WM__SendMessageIfEnabled.c \
./GUI/WM/WM_StayOnTop.c \
./GUI/WM/WM_GetInsideRectExScrollbar.c \
./GUI/WM/WM_GetInsideRect.c \
./GUI/WM/WM__GetFocussedChild.c \
./GUI/WM/WM__IsChild.c \
./GUI/WM/WM_GetWindowRect.c \
./GUI/WM/WM_Hide.c \
./GUI/WM/WM__GetFirstSibling.c \
./GUI/WM/WM_SetpfPollPID.c \
./GUI/WM/WM__GetPrevSibling.c \
./GUI/WM/WM_Move.c \
./GUI/WM/WM_Validate.c \
./GUI/WM/WM_GetWindowSize.c \
./GUI/WM/WM_GetClientWindow.c \
./GUI/WM/WM_SetTransState.c \
./GUI/WM/WM_SetCreateFlags.c \
./GUI/WM/WM_PaintWindowAndDescs.c \
./GUI/WM/WM_AttachWindow.c \
./GUI/WM/WM_GetFlags.c \
./GUI/WM/WM_SetCallback.c \
./GUI/WM/WM_BringToBottom.c \
./GUI/WM/WM_SetYSize.c \
./GUI/WM/WM__NotifyVisChanged.c \
./GUI/WM/WM_SetSize.c \
./GUI/WM/WM_TimerExternal.c \
./GUI/WM/WM_SetScrollbar.c \
./GUI/WM/WM_Timer.c \
./GUI/WM/WM_UpdateWindowAndDescs.c \
./GUI/WM/WM_GetOrg.c \
./GUI/WM/WM_BringToTop.c \
./GUI/WM/WM_GetInvalidRect.c \
./GUI/WM/WM_SetUserClipRect.c \
./GUI/WM/WM_NotifyParent.c \
./GUI/WM/WM__GetLastSibling.c \
./GUI/WM/WM_HasFocus.c \
./GUI/WM/WM_CheckScrollPos.c \
./GUI/WM/WM_GetDesktopWindowEx.c \
./GUI/WM/WM_IsEnabled.c \
./GUI/WM/WM_SetFocusOnPrevChild.c \
./GUI/WM/WM_GetFirstChild.c \
./GUI/WM/WM_Broadcast.c \
./GUI/WM/WM_ResizeWindow.c \
./GUI/WM/WM_SetScrollState.c \
./GUI/WM/WM_PID__GetPrevState.c \
./GUI/WM/WM__ForEachDesc.c \
./GUI/WM/WM_GetScrollbar.c \
./GUI/WM/WM_GetScrollPartner.c \
./GUI/WM/WM_Screen2Win.c \
./GUI/WM/WM_SetAnchor.c \
./GUI/WM/WM_GetId.c \
./GUI/WM/WM_MoveChildTo.c \
./GUI/WM/WM__IsAncestor.c \
./GUI/WM/WM_Show.c \
./GUI/WM/WM__IsEnabled.c \
./GUI/WM/WM_GetPrevSibling.c \
./GUI/WM/WM_Paint.c \
./GUI/WM/WM_OnKey.c \
./GUI/WM/WM_GetParent.c \
./GUI/WM/WM_GetDialogItem.c \
./GUI/WM/WM_CriticalHandle.c \
./GUI/WM/WM_SIM.c \
./GUI/WM/WMTouch.c \
./GUI/WM/WM_EnableWindow.c \
./GUI/MultiLayer/LCD_2.c \
./GUI/MultiLayer/LCD_4.c \
./GUI/MultiLayer/LCD_1.c \
./GUI/MultiLayer/LCD_3.c \
./GUI/Font/F6x8.c \
./GUI/Font/F8x13_ASCII.c \
./GUI/Font/F24_1.c \
./GUI/Font/F32_1.c \
./GUI/Font/F10_1.c \
./GUI/Font/F24B_ASCII.c \
./GUI/Font/F08_1.c \
./GUI/Font/FComic18B_ASCII.c \
./GUI/Font/F8x13_1.c \
./GUI/Font/F8x8.c \
./GUI/Font/F24_ASCII.c \
./GUI/Font/F32_ASCII.c \
./GUI/Font/FD60x80.c \
./GUI/Font/F13_1.c \
./GUI/Font/F13H_ASCII.c \
./GUI/Font/F08_ASCII.c \
./GUI/Font/F13B_1.c \
./GUI/Font/FD80.c \
./GUI/Font/FD36x48.c \
./GUI/Font/FComic24B_1.c \
./GUI/Font/F8x16.c \
./GUI/Font/F8x12_ASCII.c \
./GUI/Font/F8x15B_ASCII.c \
./GUI/Font/F16_ASCII.c \
./GUI/Font/F32B_ASCII.c \
./GUI/Font/F13_ASCII.c \
./GUI/Font/F32B_1.c \
./GUI/Font/FComic24B_ASCII.c \
./GUI/Font/FD48x64.c \
./GUI/Font/F16_1HK.c \
./GUI/Font/FComic18B_1.c \
./GUI/Font/F8x15B_1.c \
./GUI/Font/FD64.c \
./GUI/Font/F24B_1.c \
./GUI/Font/F13B_ASCII.c \
./GUI/Font/F8x10_ASCII.c \
./GUI/Font/F13H_1.c \
./GUI/Font/F13HB_ASCII.c \
./GUI/Font/FD48.c \
./GUI/Font/F4x6.c \
./GUI/Font/FD32.c \
./GUI/Font/F13HB_1.c \
./GUI/Font/F16_1.c \
./GUI/Font/F16B_ASCII.c \
./GUI/Font/F10S_ASCII.c \
./GUI/Font/F10_ASCII.c \
./GUI/Font/F16B_1.c \
./GUI/Font/F10S_1.c \
./GUI/Font/FD24x32.c \
./GUI/Font/F16_HK.c \
./GUI/ConvertColor/LCDP323.c \
./GUI/ConvertColor/LCDP8666.c \
./GUI/ConvertColor/LCDPM444_16.c \
./GUI/ConvertColor/LCDPM323.c \
./GUI/ConvertColor/LCDP655.c \
./GUI/ConvertColor/LCDPM888.c \
./GUI/ConvertColor/LCDP8666_1.c \
./GUI/ConvertColor/LCDP444_12.c \
./GUI/ConvertColor/LCDP888.c \
./GUI/ConvertColor/LCDPM233.c \
./GUI/ConvertColor/LCDP444_12_1.c \
./GUI/ConvertColor/LCDPM565.c \
./GUI/ConvertColor/LCDPM666.c \
./GUI/ConvertColor/LCDPM655.c \
./GUI/ConvertColor/LCDPM332.c \
./GUI/ConvertColor/LCDP111.c \
./GUI/ConvertColor/LCDP444_16.c \
./GUI/ConvertColor/LCDPM444_12.c \
./GUI/ConvertColor/LCDP666.c \
./GUI/ConvertColor/LCDPM556.c \
./GUI/ConvertColor/LCDP233.c \
./GUI/ConvertColor/LCDP332.c \
./GUI/ConvertColor/LCDP556.c \
./GUI/ConvertColor/LCDP222.c \
./GUI/ConvertColor/LCDP565.c \
./GUI/ConvertColor/LCDP555.c \
./GUI/ConvertColor/LCDPM555.c \
./GUI/ConvertMono/LCDP4.c \
./GUI/ConvertMono/LCDP2.c \
./GUI/ConvertMono/LCDP0.c \
./GUI/MemDev/GUIDEV_Auto.c \
./GUI/MemDev/GUIDEV_Measure.c \
./GUI/MemDev/GUIDEV_XY2PTR.c \
./GUI/MemDev/GUIDEV_ReduceYSize.c \
./GUI/MemDev/GUIDEV_1.c \
./GUI/MemDev/GUIDEV.c \
./GUI/MemDev/GUIDEV_WriteEx.c \
./GUI/MemDev/GUIDEV_CmpWithLCD.c \
./GUI/MemDev/GUIDEV_Banding.c \
./GUI/MemDev/GUIDEV_GetDataPtr.c \
./GUI/MemDev/GUIDEV_WriteAlpha.c \
./GUI/MemDev/GUIDEV_AA.c \
./GUI/MemDev/GUIDEV_GetXSize.c \
./GUI/MemDev/GUIDEV_Usage.c \
./GUI/MemDev/GUIDEV_Write.c \
./GUI/MemDev/GUIDEV_Clear.c \
./GUI/MemDev/GUIDEV_8.c \
./GUI/MemDev/GUIDEV_GetYSize.c \
./GUI/MemDev/GUIDEV_CreateFixed.c \
./GUI/MemDev/GUIDEV_UsageBM.c \
./GUI/MemDev/GUIDEV_SetOrg.c \
./GUI/MemDev/GUIDEV_CopyFromLCD.c \
./GUI/MemDev/GUIDEV_16.c \
./GUI/LCDDriver/LCDWin.c \
./GUI/Widget/DROPDOWN_InsertString.c \
./GUI/Widget/TEXT_SetText.c \
./GUI/Widget/DROPDOWN_SetTextAlign.c \
./GUI/Widget/LISTVIEW_GetSel.c \
./GUI/Widget/LISTBOX_MultiSel.c \
./GUI/Widget/SLIDER_SetFocusColor.c \
./GUI/Widget/BUTTON_SelfDraw.c \
./GUI/Widget/FRAMEWIN_Default.c \
./GUI/Widget/LISTVIEW_Create.c \
./GUI/Widget/CHECKBOX_SetText.c \
./GUI/Widget/LISTVIEW_GetNumRows.c \
./GUI/Widget/FRAMEWIN_SetResizeable.c \
./GUI/Widget/EDIT_SetSel.c \
./GUI/Widget/TEXT_SetTextAlign.c \
./GUI/Widget/TEXT.c \
./GUI/Widget/CHECKBOX_GetText.c \
./GUI/Widget/MENU_InsertItem.c \
./GUI/Widget/MENU_DisableItem.c \
./GUI/Widget/GRAPH_DATA_YT.c \
./GUI/Widget/LISTBOX_SetTextColor.c \
./GUI/Widget/PROGBAR_SetTextPos.c \
./GUI/Widget/HEADER_Create.c \
./GUI/Widget/FRAMEWIN_SetFont.c \
./GUI/Widget/PROGBAR.c \
./GUI/Widget/BUTTON_Bitmap.c \
./GUI/Widget/SCROLLBAR.c \
./GUI/Widget/LISTVIEW_GetItemText.c \
./GUI/Widget/CHECKBOX_GetState.c \
./GUI/Widget/CHECKBOX_SetBkColor.c \
./GUI/Widget/LISTVIEW_DeleteAllRows.c \
./GUI/Widget/FRAMEWIN_IsMinMax.c \
./GUI/Widget/MESSAGEBOX.c \
./GUI/Widget/EDITFloat.c \
./GUI/Widget/SCROLLBAR_Defaults.c \
./GUI/Widget/LISTVIEW_GetFont.c \
./GUI/Widget/LISTVIEW_SetGridVis.c \
./GUI/Widget/RADIO_Image.c \
./GUI/Widget/CHECKBOX.c \
./GUI/Widget/LISTVIEW.c \
./GUI/Widget/LISTBOX_ItemSpacing.c \
./GUI/Widget/CHECKBOX_IsChecked.c \
./GUI/Widget/DROPDOWN_SetBkColor.c \
./GUI/Widget/EDIT_SetpfAddKeyEx.c \
./GUI/Widget/BUTTON_CreateIndirect.c \
./GUI/Widget/CHECKBOX_SetFocusColor.c \
./GUI/Widget/EDITUlong.c \
./GUI/Widget/DROPDOWN_ItemSpacing.c \
./GUI/Widget/EDIT_SetpfUpdateBuffer.c \
./GUI/Widget/DROPDOWN_SetScrollbarWidth.c \
./GUI/Widget/SLIDER_CreateIndirect.c \
./GUI/Widget/HEADER_BMP.c \
./GUI/Widget/MENU_SetItem.c \
./GUI/Widget/FRAMEWIN_SetBorderSize.c \
./GUI/Widget/HEADER_SetDragLimit.c \
./GUI/Widget/PROGBAR_SetTextColor.c \
./GUI/Widget/GUI_EditHex.c \
./GUI/Widget/BUTTON_SetFocusColor.c \
./GUI/Widget/GRAPH.c \
./GUI/Widget/TEXT_SetTextColor.c \
./GUI/Widget/SCROLLBAR_SetColor.c \
./GUI/Widget/HEADER_CreateIndirect.c \
./GUI/Widget/RADIO_CreateIndirect.c \
./GUI/Widget/FRAMEWIN_SetTitleVis.c \
./GUI/Widget/LISTVIEW_GetTextColor.c \
./GUI/Widget/TEXT_Create.c \
./GUI/Widget/CHECKBOX_SetBoxBkColor.c \
./GUI/Widget/BUTTON_StreamedBitmap.c \
./GUI/Widget/LISTBOX_Default.c \
./GUI/Widget/EDIT_SetFocussable.c \
./GUI/Widget/EDIT_GetCursorPixelPos.c \
./GUI/Widget/LISTVIEW_SetAutoScroll.c \
./GUI/Widget/DROPDOWN_SetFont.c \
./GUI/Widget/LISTBOX_SetTextAlign.c \
./GUI/Widget/PROGBAR_SetMinMax.c \
./GUI/Widget/GRAPH_CreateIndirect.c \
./GUI/Widget/LISTBOX.c \
./GUI/Widget/TEXT_SetWrapMode.c \
./GUI/Widget/WIDGET.c \
./GUI/Widget/LISTBOX_SetScrollbarWidth.c \
./GUI/Widget/LISTBOX_GetItemText.c \
./GUI/Widget/HEADER_Bitmap.c \
./GUI/Widget/HEADER_StreamedBitmap.c \
./GUI/Widget/RADIO_SetBkColor.c \
./GUI/Widget/MULTIPAGE.c \
./GUI/Widget/EDITDec.c \
./GUI/Widget/LISTVIEW_SetRBorder.c \
./GUI/Widget/MULTIPAGE_Default.c \
./GUI/Widget/LISTBOX_GetTextAlign.c \
./GUI/Widget/EDITBin.c \
./GUI/Widget/GUI_EditString.c \
./GUI/Widget/BUTTON_BMP.c \
./GUI/Widget/LISTBOX_SetAutoScroll.c \
./GUI/Widget/FRAMEWIN_ButtonClose.c \
./GUI/Widget/GUI_DRAW_Self.c \
./GUI/Widget/EDIT_CreateIndirect.c \
./GUI/Widget/GUI_DRAW_STREAMED.c \
./GUI/Widget/MENU_CreateIndirect.c \
./GUI/Widget/TEXT_CreateIndirect.c \
./GUI/Widget/BUTTON_Create.c \
./GUI/Widget/MENU_SetBorderSize.c \
./GUI/Widget/EDIT_GetCursorPos.c \
./GUI/Widget/MENU_Attach.c \
./GUI/Widget/LISTBOX_SetString.c \
./GUI/Widget/LISTBOX_SetOwner.c \
./GUI/Widget/WIDGET_Effect_3D2L.c \
./GUI/Widget/FRAMEWIN_MinMaxRest.c \
./GUI/Widget/LISTBOX_ItemDisabled.c \
./GUI/Widget/CHECKBOX_SetNumStates.c \
./GUI/Widget/RADIO_SetFocusColor.c \
./GUI/Widget/GUI_EditBin.c \
./GUI/Widget/CHECKBOX_SetState.c \
./GUI/Widget/GUI_ARRAY_ResizeItem.c \
./GUI/Widget/EDIT_GetNumChars.c \
./GUI/Widget/RADIO.c \
./GUI/Widget/LISTVIEW_SetTextColor.c \
./GUI/Widget/DROPDOWN_SetAutoScroll.c \
./GUI/Widget/LISTVIEW_GetNumColumns.c \
./GUI/Widget/MENU_Default.c \
./GUI/Widget/DROPDOWN_Default.c \
./GUI/Widget/DROPDOWN_SetTextHeight.c \
./GUI/Widget/LISTBOX_DeleteItem.c \
./GUI/Widget/MENU.c \
./GUI/Widget/PROGBAR_Create.c \
./GUI/Widget/FRAMEWIN_Create.c \
./GUI/Widget/LISTVIEW_Default.c \
./GUI/Widget/GUI_DRAW_BITMAP.c \
./GUI/Widget/CHECKBOX_Create.c \
./GUI/Widget/EDIT_SetTextMode.c \
./GUI/Widget/MULTIEDIT.c \
./GUI/Widget/CHECKBOX_SetDefaultImage.c \
./GUI/Widget/GUI_ARRAY_InsertItem.c \
./GUI/Widget/LISTVIEW_SetBkColor.c \
./GUI/Widget/GUI_EditFloat.c \
./GUI/Widget/LISTVIEW_SetTextAlign.c \
./GUI/Widget/LISTVIEW_DeleteRow.c \
./GUI/Widget/MULTIEDIT_CreateIndirect.c \
./GUI/Widget/CHECKBOX_SetTextAlign.c \
./GUI/Widget/RADIO_GetText.c \
./GUI/Widget/SCROLLBAR_CreateIndirect.c \
./GUI/Widget/EDIT.c \
./GUI/Widget/TEXT_SetFont.c \
./GUI/Widget/FRAMEWIN_CreateIndirect.c \
./GUI/Widget/CHECKBOX_SetFont.c \
./GUI/Widget/RADIO_SetTextColor.c \
./GUI/Widget/DROPDOWN_SetTextColor.c \
./GUI/Widget/FRAMEWIN_Get.c \
./GUI/Widget/FRAMEWIN_SetTitleHeight.c \
./GUI/Widget/MULTIEDIT_Create.c \
./GUI/Widget/RADIO_SetDefaultImage.c \
./GUI/Widget/MENU_SetTextColor.c \
./GUI/Widget/LISTVIEW_UserData.c \
./GUI/Widget/FRAMEWIN__UpdateButtons.c \
./GUI/Widget/LISTBOX_GetNumItems.c \
./GUI/Widget/DROPDOWN_GetNumItems.c \
./GUI/Widget/MENU_SetFont.c \
./GUI/Widget/CHECKBOX_SetTextColor.c \
./GUI/Widget/LISTVIEW_SetItemColor.c \
./GUI/Widget/BUTTON_GetBitmap.c \
./GUI/Widget/LISTVIEW_SetItemText.c \
./GUI/Widget/DROPDOWN.c \
./GUI/Widget/LISTBOX_SetBkColor.c \
./GUI/Widget/MENU_SetBkColor.c \
./GUI/Widget/LISTVIEW_CreateIndirect.c \
./GUI/Widget/MENU_DeleteItem.c \
./GUI/Widget/BUTTON_SetTextAlign.c \
./GUI/Widget/HEADER.c \
./GUI/Widget/WIDGET_SetEffect.c \
./GUI/Widget/EDIT_Create.c \
./GUI/Widget/RADIO_Create.c \
./GUI/Widget/LISTBOX_SetOwnerDraw.c \
./GUI/Widget/FRAMEWIN_Button.c \
./GUI/Widget/RADIO_SetText.c \
./GUI/Widget/LISTBOX_CreateIndirect.c \
./GUI/Widget/PROGBAR_SetFont.c \
./GUI/Widget/PROGBAR_SetText.c \
./GUI/Widget/RADIO_Default.c \
./GUI/Widget/CHECKBOX_SetImage.c \
./GUI/Widget/PROGBAR_SetTextAlign.c \
./GUI/Widget/EDITHex.c \
./GUI/Widget/GUI_DRAW_BMP.c \
./GUI/Widget/GUI_ARRAY.c \
./GUI/Widget/DROPDOWN_Create.c \
./GUI/Widget/LISTVIEW_SetColumnWidth.c \
./GUI/Widget/MENU_GetItemText.c \
./GUI/Widget/LISTVIEW_GetHeader.c \
./GUI/Widget/SCROLLBAR_Create.c \
./GUI/Widget/LISTVIEW_SetRowHeight.c \
./GUI/Widget/SCROLLBAR_SetWidth.c \
./GUI/Widget/WINDOW.c \
./GUI/Widget/DROPDOWN_AddString.c \
./GUI/Widget/WIDGET_Effect_Simple.c \
./GUI/Widget/LISTBOX_Font.c \
./GUI/Widget/FRAMEWIN.c \
./GUI/Widget/LISTVIEW_DeleteColumn.c \
./GUI/Widget/WIDGET_SetWidth.c \
./GUI/Widget/PROGBAR_CreateIndirect.c \
./GUI/Widget/DROPDOWN_CreateIndirect.c \
./GUI/Widget/SLIDER_Create.c \
./GUI/Widget/CHECKBOX_Image.c \
./GUI/Widget/PROGBAR_SetBarColor.c \
./GUI/Widget/MENU_GetItem.c \
./GUI/Widget/MENU_GetNumItems.c \
./GUI/Widget/FRAMEWIN_ButtonMin.c \
./GUI/Widget/LISTVIEW_SetSort.c \
./GUI/Widget/WIDGET_FillStringInRect.c \
./GUI/Widget/MULTIPAGE_Create.c \
./GUI/Widget/SLIDER.c \
./GUI/Widget/FRAMEWIN_SetColors.c \
./GUI/Widget/FRAMEWIN_ButtonMax.c \
./GUI/Widget/LISTVIEW_DisableRow.c \
./GUI/Widget/RADIO_SetImage.c \
./GUI/Widget/MENU_EnableItem.c \
./GUI/Widget/HEADER_GetSel.c \
./GUI/Widget/WIDGET_Effect_3D.c \
./GUI/Widget/CHECKBOX_Default.c \
./GUI/Widget/WIDGET_Effect_3D1L.c \
./GUI/Widget/SLIDER_Default.c \
./GUI/Widget/GUI_EditDec.c \
./GUI/Widget/DROPDOWN_SetScrollbarColor.c \
./GUI/Widget/BUTTON_Get.c \
./GUI/Widget/LISTBOX_ScrollStep.c \
./GUI/Widget/MENU__FindItem.c \
./GUI/Widget/GRAPH_DATA_XY.c \
./GUI/Widget/LISTVIEW_InsertRow.c \
./GUI/Widget/RADIO_SetGroupId.c \
./GUI/Widget/LISTBOX_Create.c \
./GUI/Widget/CHECKBOX_SetSpacing.c \
./GUI/Widget/DROPDOWN_SetColor.c \
./GUI/Widget/DIALOG.c \
./GUI/Widget/EDIT_SetCursorAtChar.c \
./GUI/Widget/CHECKBOX_CreateIndirect.c \
./GUI/Widget/LISTBOX_InsertString.c \
./GUI/Widget/FRAMEWIN_AddMenu.c \
./GUI/Widget/BUTTON__SetBitmapObj.c \
./GUI/Widget/HEADER__SetDrawObj.c \
./GUI/Widget/LISTVIEW_SetSel.c \
./GUI/Widget/WIDGET_Effect_None.c \
./GUI/Widget/BUTTON.c \
./GUI/Widget/GUI_DRAW.c \
./GUI/Widget/DROPDOWN_DeleteItem.c \
./GUI/Widget/BUTTON_IsPressed.c \
./GUI/Widget/LISTBOX_SetScrollbarColor.c \
./GUI/Widget/EDIT_Default.c \
./GUI/Widget/BUTTON_Default.c \
./GUI/Widget/WINDOW_Default.c \
./GUI/Widget/GRAPH_SCALE.c \
./GUI/Widget/TEXT_Default.c \
./GUI/Widget/TEXT_SetBkColor.c \
./GUI/Widget/LISTVIEW_SetLBorder.c \
./GUI/Widget/GUI_HOOK.c \
./GUI/Widget/MULTIPAGE_CreateIndirect.c \
./GUI/Widget/LISTVIEW_GetBkColor.c \
./GUI/Widget/GUI_ARRAY_DeleteItem.c \
./GUI/Widget/SCROLLBAR_GetValue.c \
./GUI/Widget/RADIO_SetFont.c \
./GUI/Widget/EDIT_SetInsertMode.c \
./GUI/Widget/MENU_Popup.c \
./GUI/Widget/LISTVIEW_SetFont.c \
./Application/GUIDemo/GUIDEMO_Bitmap4bpp.c \
./Application/GUIDemo/GUIDEMO_WM.c \
./Application/GUIDemo/GUIDEMO_ColorBar.c \
./Application/GUIDemo/GUIDEMO_Circle.c \
./Application/GUIDemo/GUIDEMO_FrameWin.c \
./Application/GUIDemo/MainTask.c \
./Application/GUIDemo/GUIDEMO_Automotive.c \
./Application/GUIDemo/GUIDEMO_Speed.c \
./Application/GUIDemo/GUIDEMO_Messagebox.c \
./Application/GUIDemo/MicriumLogoWRed.c \
./Application/GUIDemo/GUIDEMO_Navi.c \
./Application/GUIDemo/GUIDEMO_Intro.c \
./Application/GUIDemo/GUIDEMO_Touch.c \
./Application/GUIDemo/GUIDEMO_LUT.c \
./Application/GUIDemo/GUIDEMO_Graph.c \
./Application/GUIDemo/GUIDEMO_Polygon.c \
./Application/GUIDemo/MicriumLogo.c \
./Application/GUIDemo/GUIDEMO_ProgBar.c \
./Application/GUIDemo/GUIDEMO_Cursor.c \
./Application/GUIDemo/GUIDEMO_MemDevB.c \
./Application/GUIDemo/GUIDEMO_Font.c \
./Application/GUIDemo/GUIDEMO.c \
./Application/GUIDemo/GUIDEMO_HardwareInfo.c \
./Application/GUIDemo/GUIDEMO_ColorList.c \
./Application/GUIDemo/GUIDEMO_Bitmap.c \
./Application/GUIDemo/GUIDEMO_Dialog.c \
-L/opt/nuc970bsp/applications/tslib-1.1/install/lib/ -lts  -ldl \
-lm -lpthread -o ucGUI

